### ISSUE TITLE
v0.9.0 roadmap

### ISSUE THREAD

**Issue by kenaniah** [utgarda/sidekiq-status#106]
Hi everyone! I wanted to put together a quick roadmap to discuss the future efforts and direction of this gem. My goal is to get an understanding of what the community would like to see in future releases so that we can prioritize and optimize our efforts. 

Please add your thoughts as comments on this thread, and use the Github reactions to add support for the ideas of others. Please keep to one feature per comment, but feel free to leave multiple comments.

To get us started, the following is a list of "requested features" according to the open pull requests:

## Requested Features

 - [x]  Error handling improvements / new `:retrying` status (#98)
 - [x]  Filter ~between all jobs and~ non-`Sidekiq::Status::Worker` jobs (#81, #91, #99, #113)
 - [x]  Ensure `ActiveJob` instances respect custom job expirations (#113)
 - [x]  Add pagination to jobs list (#103, #118 )
 - [x]  Configure the number of jobs to display per page (#95, #119 )
 - [x]  Add a button to the UI to remove a job from the status list (#92, #114)
 - [x]  Add a button in the UI to retry a failed job from the status list (#114)

**Comment by GaudamThiyagarajan** [comment]
Also you can have retry right next to it incase the job has failed
